### ISSUE TITLE
React Devtool plugin

### ISSUE THREAD

**Issue by Viktor-82** [atls-academy/viktor82.github.io#3]
### Описание бага

I don't see the components according to the instructions when working with the React Devtool plugin.

### Воспроизведение

Procedure
1) Install React Devtools extension for Chrome
2) Registration on codepen.io with notification by mail and account activation via the link received by mail.
3) Clicking the Fork button in the bottom right corner of the codepen
! the beginning of discrepancies between instructions and reality!
Change View - it's not clear what it is. I did not come up with anything better than calling the debug mode in the browser by pressing f12.
In the panel, I found the appearance of the Components and Profiler items of the React Devools plugin
When I click on the Components tab, I don't see the components listed in the official online documentation (Game, Board, Square). There are many others.

### Ожидаемое поведение

According to the official doc, while on the  
(https://codepen.io/web_dev_335/pen/xxzaNry?editors=0010)  
 when using the plugin React Devtools 
 I have to see the components "Game" "Board" "Square"

### Материалы

what should be
![image](https://user-images.githubusercontent.com/84030812/205013444-09c15355-cf9e-4806-abcf-02fd736527cf.png)

what is actually
![image](https://user-images.githubusercontent.com/84030812/205013934-1e0f629f-ae93-47b4-bdf8-a46bdb1a2560.png)

### Данные окружения

Win 10

Google Chrome 107.0.5304.123

**Comment by TFK70** [comment]
@Viktor-82 вообще мы не пользуемся этим плагином

То, что ты видишь - это результат интерпретации кода из бандла. Изначально ты пишешь код на тайпскрипте, но V8 понимает только JS. Для этого код на тайпскрипт компилируется в код на js. Эту задачу у нас выполняет сборщик - webpack (но это не основная его задача), ты его на проекте нигде не видишь, потому что он настроен в [tools](https://github.com/atls/tools). Мы используем tools на всех проектах чтобы не переписывать каждый раз конфиги вебпака, линтера и тайпскрипта по-новой

Так вот, помимо компиляции ts кода в js, вебпак также занимается оптимизацией кода. Результат всех шаманств вебпака над кодом складывается в 1 js файл в папку `dist`, это и называется бандлом. Дерево в реакт девтулз, которое ты увидел - это результат оптимизации. Человеку не понятно, но компу проще
