### ISSUE TITLE
Не могу запустить и увидеть инструменты uikit

### ISSUE THREAD

**Issue by Viktor-82** [atls-academy/viktor82.github.io#5]
### Описание бага

Не могу запустить и увидеть инструменты (элементы) входящие в состав пакета uikit

### Воспроизведение

1. Нахожусь в директории uikit запускаю команду:
yarn workspace @atls-ui-proto/design dev  
получаю:
 Error.captureStackTrace(firstError);
            ^

Error: Required unplugged package missing from disk. This may happen when switching branches without running installs (unplugged packages must be fully materialized on disk to work).

Missing package: core-js@npm:3.14.0
Expected package location: /home/alfa/Рабочий стол/Atlantis/uikit/.yarn/unplugged/core-js-npm-3.14.0-29d8f94441/node_modules/core-js/

### Ожидаемое поведение

Предполагаю что должен визуально увидеть элементы дизайна очевидно в браузере. 

### Материалы

Error.captureStackTrace(firstError);
            ^

Error: Required unplugged package missing from disk. This may happen when switching branches without running installs (unplugged packages must be fully materialized on disk to work).

Missing package: core-js@npm:3.14.0
Expected package location: /home/alfa/Рабочий стол/Atlantis/uikit/.yarn/unplugged/core-js-npm-3.14.0-29d8f94441/node_modules/core-js/

### Данные окружения

Ubuntu 22.04
WebStorm Build #WS-223.7571.168
Node 16.13.2
npm 8.1.2

ввожу команду 
yarn -v получаю:
0.0.1-git.20220605.hash-c4f9c8f

**Comment by TFK70** [comment]
@Viktor-82 пакеты через `yarn` устанавливались? Там нет ошибок?

**Comment by Viktor-82** [comment]
Пакеты устанавливал командой `yarn install`.
При установке `Error` нигде не вижу, везде надписи `Completed`.
При запуске команды `yarn workspace @atls-ui-proto/design dev` идет запуск и появляется окно 
`Storybook 6.5.9 for React started`  и адреса `Local` и `Network` при переходе на которые в браузере данные не отображаются, внизу окна присутствует ошибка.
Также в этом окне все время вылетает надпись `Upgrade now: npx storybook@latest upgrade`
Делаю обновление предложенной командой,
запускал ту же команду с заменой `npx` на `yarn` вылетает ошибка. 

Снова запускаю `yarn workspace` результать вижу тот же.
Текст ошибки под окном:

```node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at module.exports (/home/alfa/Рабочий
стол/Atlantis/uikit/.yarn/cache/open-npm-7.4.2-a378c23959-3333900ec0.zip/node_modules/open/index.js:175:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawn'
}
```

**Comment by TFK70** [comment]
какая версия ноды?

**Comment by Viktor-82** [comment]
Версия ноды `Node 16.13.2`

**Comment by Viktor-82** [comment]
Спасибо за помощь! Решено.
